### PR TITLE
Delete Global Variable in NLP_TO_NETWORK.py

### PR DESCRIPTION
**Pull request by Robin888**
Which probably led to memory error.

### CODE REVIEW

**Comment by rsteed11** [comment]
@Ruobing Do you want this in the next AWS push?

**Comment by Robin888** [comment]
@rsteed11 I think we should push it to AWS today, since it is a fundamental problem

**Comment by rsteed11** [comment]
@Robin888 In that case, let me know when you've merged to master and I'll deploy

**Comment by Robin888** [comment]
@rsteed11 No problem. I will close this merge request and merge it to master branch

**Pull request merged**
